### PR TITLE
Required steps

### PR DESCRIPTION
**Pull request by jkmaxwell**

### CODE REVIEW

**Comment by alexfruehwirth** [comment]
Does the app not work with the original credentials?

**Comment by jkmaxwell** [comment]
It...shouldn't! I guess i didn't think to try that. Sorry. Will try
now.

**Comment by alexfruehwirth** [comment]
thx. 

i just mentioned the credentials thing yesterday, because i thought this could be a quickfix. 
but you should be able to use the original creds.

**Comment by jkmaxwell** [comment]
Oh wow, yes, it works.
Perfect!

**Comment by alexfruehwirth** [comment]
once again, thanks for testing! :)

**Pull request closed without merging**
